Export scaling system
X-Hax/sadx-mod-loader pull request #81
Opened 2021-05-01 20:10 UTC by kellsnc

This puts the needed functions for scaling HUDs outside of the mod loader in HelperFunctions.

What do you think? I made a copy of the scaling enums to avoid having to include `uiscale.h`, I don't know if that's appropriate.

2021-05-02 02:27 UTC, michael-fadely commented
The enums ought to be unified in one place. Casting form one enum to another is prone to error and increases work load should they need to change, as both must be carefully updated to match.

Maybe we could add another header (as a public include) that just has the original enums in the uiscale namespace? Then both of these headers can include this unified header and share the same enums.

On that note: any enums that are public/api-facing need to be fully documented as well.

2021-05-05 04:34 UTC, michael-fadely commented
As I was drafting up some inline documentation for the enums, it occurred to me that the current `Align` enum allows you to specify values that make no sense, like `Align::left | Align::right`.

I'm thinking that this ought to be tightened up before the API is made public so that we avoid making breaking changes after it's available. I'll see what I can come up with.

2021-05-05 13:16 UTC, kellsnc commented
@michael-fadely  Maybe by "hardcoding" the possibiltiies?

```
enum { 
  automatic,
  top_left, top, top_right
  center_left, center, center_right
  bottom_left, bottom, bottom_right
}
```

2021-06-01 01:31 UTC, michael-fadely commented
I've done some work on a branch here: https://github.com/sonicretro/sadx-mod-loader/tree/uiscale-api-prep

Critically, it checks that the UI scale stack is empty at the end of each frame. However, it's not currently considered a critical error, and it probably ought to be. If there is a push and no matching pop, chances are that too many pushes will continue to happen and the stack will leak memory. (I just realized all this last second 😅)

If you could update your PR to these changes, then I think this is OK to push through. Let me know if you have any concerns. Sorry for taking so long!

2021-06-02 10:20 UTC, kellsnc commented
Thanks a lot! :)

I've merged the changes and will test the PR later. 
Did you take a look at the "documentation" I wrote in SADXModInfo? I don't know if it's good enough.

> Critically, it checks that the UI scale stack is empty at the end of each frame. However, it's not currently considered a critical error, and it probably ought to be. If there is a push and no matching pop, chances are that too many pushes will continue to happen and the stack will leak memory. (I just realized all this last second 😅)

Should I make the error critical then?

2021-06-06 01:14 UTC, michael-fadely commented
Should be OK for now. Just need to make a note to change it later.

2021-06-06 01:18 UTC, michael-fadely requested changes
Just need one thing fixed. Otherwise, LGTM.

2021-06-06 01:18 UTC, michael-fadely commented on SADXModLoader/include/ScaleInfo.h
> +		 * \brief Automatically align the canvas
My fault here, but I did finish writing this line on the branch I linked earlier.

2021-06-06 17:07 UTC, merged